server:
  port: 80
eureka:
  client:
    register-with-eureka: true #是否将自己注册到eureka
    service-url:
    #defaultZone: http://localhost:7001/eureka
    defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
#设置fegin客户端超时时间（openfeign默认支持ribbon）
ribbon:
#指的是建立连接所用的时间，适用于网络情况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000
logging:
  level:
    com.towery.springcloud.service.PaymentFeignService.get: debug
